services:
  # Servidor Backend (Node.js + Express + WebSockets)
  backend:
    container_name: streampro_backend
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      # Ligação ao serviço "mongodb" em vez de "localhost"
      - MONGODB_URI=mongodb://mongodb:27017/streaming_chat
      - REDIS_HOST=redis
      - JWT_SECRET=chave_secreta_super_segura
      - PORT=3000
    depends_on:
      - mongodb
      - redis
# --- FRONTEND (React + Vite) ---
  frontend:
    container_name: streampro_frontend
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true # Essencial para o Windows atualizar em tempo real
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  # --- Infraestrutura de Base de Dados NoSQL(MongoDB) ---
  mongodb:
    image: mongo:latest
    container_name: streampro_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # --- Infraestrutura de Cache (Redis) ---
  redis:
    image: redis:alpine
    container_name: streampro_redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
